### ISSUE TITLE
Change the nterpolation Value

### ISSUE THREAD

**Issue by Jerchongkong** [CM-BF/FeatureFlow#1]
Hi m8 you are doing a good job.
I want to know how to change the interpolation value in video, currently it can only be done 2x and I need to do it at a higher value, 4x 6x etc.

keep it up!

**Comment by CM-BF** [comment]
Hi, thank you for your issue.

1. Because of the non-linear assumption (you will find it in the paper), 6x interpolation is not supported, but you can interpolate videos 2x, 4x, 8x, etc.
2. We will support modifying the interpolation value soon.

If you are hurried to test it, there are two solutions:
1) Modify pure_run.py to fit your demand.
2) Use video_processing.py more times (we don't recommend you to do it, because that means many times encoding and decoding which cause damage to the video).

Have fun!

**Comment by CM-BF** [comment]
sequence_run.py is updated.
