### ISSUE TITLE
Runtime performance

### ISSUE THREAD

**Issue by pepinu** [CM-BF/FeatureFlow#9]
Hello,

In the paper, nor the supplement, I haven't seen any performance regarding Runtime/FPS for different sizes.

Do you have any ballpark numbers, how fast is FeatureFlow vs DAIN for example on 360p and 720p videos? 

Best regards

**Comment by CM-BF** [comment]
Hi,

I did not quantify the Runtime, but I am sure it runs fast than DAIN according to the video generation test before. That is a good question. I'd like to do so and I also find a way to run much faster or get much better performance than what I showed in the paper, but I cannot because as I mention in `README.md`, I had left the Lab.

Thank you!

If you want to do some experiments on it, please contact me if any questions.
